### ISSUE TITLE
HeadsetDetection.m:9:33: error: no visible @interface for 'CDVPluginResult' declares the selector 'toSuccessCallbackString

### ISSUE THREAD

**Issue by scamianbas** [EddyVerbruggen/HeadsetDetection-PhoneGap-Plugin#4]
Hi @EddyVerbruggen ,
when building the plugin with an ionic app for ios, I'm getting an error with cordova-ios-4 but it's working with iOS@3.9.2 with a deprecation warning (see details below).
Sorry not being able to help you as I do not have any knowledge about objectiveC ...
Thank you very much for the fix,
Mirko

ios@3.9.2 :
/Users/mirko/myApp080316/platforms/ios/CPM App/Plugins/nl.x-services.plugins.headsetdetection/HeadsetDetection.m:9:9: warning: 'writeJavascript:' is deprecated: Deprecated in Cordova 3.6. Use the CDVCommandDelegate equivalent of evalJs:. This will be removed in 4.0.0 [-Wdeprecated-declarations]

[self writeJavascript:[result toSuccessCallbackString:callbackId]];

```
^
```

ios@4.0.0 , ios@4.0.1 , ios@4.1.0 : 
/Users/mirko/myApp080316/platforms/ios/CPM App/Plugins/nl.x-services.plugins.headsetdetection/HeadsetDetection.m:9:33: error: no visible @interface for 'CDVPluginResult' declares the selector 'toSuccessCallbackString:'

[self writeJavascript:[result toSuccessCallbackString:callbackId]];

```
                 ~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~
```

1 error generated.

*\* BUILD FAILED **

**Comment by EddyVerbruggen** [comment]
Thanks for the extensive bugreport. I just released v 2.0.0 [to npm](https://www.npmjs.com/package/cordova-plugin-headsetdetection) which I encourage you to use.

Warning: the plugin id changed, so please remove the old one, then add the new one.

**Comment by scamianbas** [comment]
This new plugin version seems ok, thank you very much !
FYI, here's what i did :

```
ionic plugin remove nl.x-services.plugins.headsetdetection
ionic plugin add cordova-plugin-headsetdetection
```
